apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: device.stable.example.com
spec:
  group: stable.example.com
  names:
    singular: device
    plural: devices
    kind: device
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deviceId:
                  type: string
                type:
                  type: string
                location:
                  type: string
                status:
                  type: integer
                  default: 0
                lastCheckIn:
                  type: integer
                  default: 0
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced