apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: example.stable.example.com
spec:
  group: stable.example.com
  names:
    plural: example
    kind: example
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                string:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced