apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-account-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: operator-account
    namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-operator-deployment
  labels:
    app: device-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: device-operator
  template:
    metadata:
      labels:
        app: device-operator
    spec:
      serviceAccountName: operator-account
      containers:
      - name: device-operator
        image: device-operator:latest
        imagePullPolicy: Never
